In [1]:
import pandas as pd
import os
import re
import numpy as np
import netCDF4 as nc
import xarray

In [4]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,4,5,6,7,8,9,10,11])
ab = np.outer(a,b)
bar = ab*np.array([[1,0,1,0,1,0,1,0,1,0,1],
                   [0,1,0,1,0,1,0,1,0,1,0],
                   [1,0,1,0,1,0,1,0,1,0,1],
                   [0,1,0,1,0,1,0,1,0,1,0]])

In [6]:
2*bar

array([[ 2,  0,  6,  0, 10,  0, 14,  0, 18,  0, 22],
       [ 0,  8,  0, 16,  0, 24,  0, 32,  0, 40,  0],
       [ 6,  0, 18,  0, 30,  0, 42,  0, 54,  0, 66],
       [ 0, 16,  0, 32,  0, 48,  0, 64,  0, 80,  0]])

latitude:
longitude: 186 buah

In [3]:
pd.options.display.max_columns = 23

In [59]:
coor.shape

(505, 22)

In [44]:
fraction_primary_data = pd.read_csv('./data/1500-2004/updated_states/gothr.1500.txt', sep=' ', names = lon_coordinates, header=None, index_col=False)
fraction_primary_data.set_index(lat_coordinates, inplace=True)
a = fraction_primary_data.loc[-0.25, 109.25]
print(f"Primary: {a}")

fraction_secondary_data = pd.read_csv('./data/1500-2004/updated_states/gsecd.1500.txt', sep=' ', names = lon_coordinates, header=None, index_col=False)
fraction_secondary_data.set_index(lat_coordinates, inplace=True)
b = fraction_secondary_data.loc[-0.25, 109.25]
print(f"Secondary: {b}")

fraction_pasture_data = pd.read_csv('./data/1500-2004/updated_states/gpast.1500.txt', sep=' ', names = lon_coordinates, header=None, index_col=False)
fraction_pasture_data.set_index(lat_coordinates, inplace=True)
c = fraction_pasture_data.loc[-0.25, 109.25]
print(f"Pasture: {c}")

fraction_crop_data = pd.read_csv('./data/1500-2004/updated_states/gcrop.1500.txt', sep=' ', names = lon_coordinates, header=None, index_col=False)
fraction_crop_data.set_index(lat_coordinates, inplace=True)
d= fraction_crop_data.loc[-0.25, 109.25]
print(f"Crop: {d}")
print()
print(f"total: {a+b+c+d}")

Primary: 0.772427
Secondary: 0.0
Pasture: 0.004111
Crop: 0.003273

total: 0.7798109999999999


In [24]:
coor = pd.read_csv('./data/1500-2004/lu/lat-0.25lon-77.75.lu', sep=' ')
coor

year   cp   pc   pv        vp   vc   cv        sc        cs        sp  \
0    1500  0.0  0.0  0.0  0.000063  0.0  0.0  0.000000  0.000000  0.000000   
1    1501  0.0  0.0  0.0  0.000067  0.0  0.0  0.000000  0.000000  0.000000   
2    1502  0.0  0.0  0.0  0.000071  0.0  0.0  0.000000  0.000000  0.000000   
3    1503  0.0  0.0  0.0  0.000076  0.0  0.0  0.000000  0.000000  0.000000   
4    1504  0.0  0.0  0.0  0.000079  0.0  0.0  0.000000  0.000000  0.000000   
..    ...  ...  ...  ...       ...  ...  ...       ...       ...       ...   
500  2000  0.0  0.0  0.0  0.000000  0.0  0.0  0.006432  0.009210  0.017713   
501  2001  0.0  0.0  0.0  0.000000  0.0  0.0  0.006247  0.009025  0.017646   
502  2002  0.0  0.0  0.0  0.000000  0.0  0.0  0.006062  0.008839  0.017578   
503  2003  0.0  0.0  0.0  0.000000  0.0  0.0  0.005877  0.008655  0.017511   
504  2004  0.0  0.0  0.0  0.000000  0.0  0.0  0.005691  0.008469  0.017443   

           ps        vs            sbh     f_sbh          vbh     f_vbh  sbh2  \
0    0.000000  0.000000       0.000000  0.000000     0.000000  0.000000   0.0   
1    0.000004  0.000094       0.000000  0.000000  4129.091591  0.000094   0.0   
2    0.000008  0.000094       0.007079  0.000000  4136.057691  0.000094   0.0   
3    0.000013  0.000094       0.014473  0.000000  4142.892461  0.000094   0.0   
4    0.000017  0.000094       0.032882  0.000000  4148.492157  0.000094   0.0   
..        ...       ...            ...       ...          ...       ...   ...   
500  0.018725  0.000000       0.000000  0.000000     0.000000  0.000000   0.0   
501  0.018658  0.000000   41517.632709  0.001321     0.000000  0.000000   0.0   
502  0.018590  0.000000  128093.011687  0.004137     0.000000  0.000000   0.0   
503  0.018523  0.000000  148441.323604  0.004870     0.000000  0.000000   0.0   
504  0.018455  0.000000  146658.100667  0.004899     0.000000  0.000000   0.0   

     f_sbh2  vbh2  f_vbh2  sbh3  f_sbh3  
0       0.0   0.0     0.0   0.0     0.0  
1       0.0   0.0     0.0   0.0     0.0  
2       0.0   0.0     0.0   0.0     0.0  
3       0.0   0.0     0.0   0.0     0.0  
4       0.0   0.0     0.0   0.0     0.0  
..      ...   ...     ...   ...     ...  
500     0.0   0.0     0.0   0.0     0.0  
501     0.0   0.0     0.0   0.0     0.0  
502     0.0   0.0     0.0   0.0     0.0  
503     0.0   0.0     0.0   0.0     0.0  
504     0.0   0.0     0.0   0.0     0.0  

[505 rows x 22 columns]

In [18]:
coor = pd.read_csv('./data/1500-2004/lu/lat-0.25lon109.25.lu', sep=' ')
coor.iloc[:,1:12].sum().sum()

0.52802

In [45]:
coor.sum()

year      8.847600e+05
cp        2.590000e-04
pc        0.000000e+00
pv        0.000000e+00
vp        3.657700e-02
vc        2.007080e-01
cv        0.000000e+00
sc        7.641000e-02
cs        6.323600e-02
sp        1.354100e-02
ps        1.099700e-02
vs        1.262920e-01
sbh       4.137963e+04
f_sbh     2.633000e-03
vbh       6.218838e+06
f_vbh     1.262920e-01
sbh2      0.000000e+00
f_sbh2    0.000000e+00
vbh2      0.000000e+00
f_vbh2    0.000000e+00
sbh3      0.000000e+00
f_sbh3    0.000000e+00
dtype: float64

In [5]:
ds['vegfract'][0,:,:,:].data.shape

(14, 360, 720)

In [40]:
sum_area = 0
count = 0
for pft in ds['vegfract'][0,:,:,:].data:
    count +=1
    print(f"pft {count}:{pft[180,578]}")
    sum_area += pft[180,578]
print()
print(f"total: {sum_area}")

pft 1:0.532689094543457
pft 2:0.0
pft 3:0.0
pft 4:0.0
pft 5:0.0
pft 6:0.0
pft 7:0.0
pft 8:0.0
pft 9:0.0
pft 10:0.0
pft 11:0.0
pft 12:0.33163341879844666
pft 13:0.01769409328699112
pft 14:0.07321590930223465

total: 0.9552325159311295


In [8]:
carbonEquDense = np.array([
     #PFT 1     2     3     4     5     6  7  8   9  10  11
    [# Biomass
     [  200,  160,  160,  135,   90,   90,27,27,  7, 18,  3], # Primary   - Veg
     [  150,  120,  120,  100,   68,   68,27,27,  7, 18,  0], # Secondary - Veg
     [   18,   18,    7,    7,    7,    7,18, 7,  7, 18,  7], # Pasture   - Veg
     [    5,    5,    5,    5,    5,    5, 5, 5,  3,  5,  1]], # Crop      - Veg
    [# Soil
     [  117,  117,  134,  134,  206,  206,69,69,189, 42,204], # Primary   - Soil
     [   88,   88,  120,  120,  185,  185,69,69,189, 42,204], # Secondary - Soil
     [87.75,87.75,100.5,100.5,154.5,154.5,69,69,189, 42,204], # Pasture   - Soil
     [   58,   58,   67,   67,  103,  103,34,34, 94, 21,101]]  # Crop      - Soil
])
carbonEquDense[0]

array([[200., 160., 160., 135.,  90.,  90.,  27.,  27.,   7.,  18.,   3.],
       [150., 120., 120., 100.,  68.,  68.,  27.,  27.,   7.,  18.,   0.],
       [ 18.,  18.,   7.,   7.,   7.,   7.,  18.,   7.,   7.,  18.,   7.],
       [  5.,   5.,   5.,   5.,   5.,   5.,   5.,   5.,   3.,   5.,   1.]])

In [60]:
a = np.array([[1,1,1,1,1],
              [1,2,3,4,5],
              [2,4,6,8,10]])
a.sum(axis=1)

array([ 5, 15, 30])

## Melihat banyak data koordinat latitude dan longitude

In [2]:
lats = []
lons = []
# os.listdir('./lu')
for filename in os.listdir('./data/1500-2004/lu'):
    lat = re.search('lat(.+?)lon', filename).group(1)
    lon = re.search('lon(.+?)\.lu', filename).group(1)
    if lat not in lats:
        lats.append(lat)
    if lon not in lons:
        lons.append(lon)
    
lats = sorted([float(i) for i in lats])
lons = sorted([float(i) for i in lons])

print(f"Banyak koordinat latitude: {len(lats)}")
print(f"Banyak koordinat longitude: {len(lons)}")

Banyak koordinat latitude: 282
Banyak koordinat longitude: 720


## Melihat metadata dari file-file di dalam folder updated_states

In [24]:
# Variabel untuk menampung nilai-nilai metadata
cols = []    # banyak koordinat longitude
rows = []    # banyak koordinat latitude
xll = []     #
yll = []     # 
sizes = []   #
nodatas = [] #
counter = 0

# os.listdir('./lu')
for file in os.listdir('./updated_states'):
    with open(f"./updated_states/{file}", 'r') as readfile:
        text = readfile.read()
        col = re.search('ncols\s+(.+?)\s', text).group(1)
        row = re.search('nrows\s+(.+?)\s', text).group(1)
        x = re.search('xllcorner\s+(.+?)\s', text).group(1)
        y = re.search('yllcorner\s+(.+?)\s', text).group(1)
        size = re.search('cellsize\s+(.+?)\s', text).group(1)
        nodata = re.search('NODATA_value\s+(.+?)\s', text).group(1)
        
        if col not in cols:
            cols.append(col)
        if row not in rows:
            rows.append(row)
        if x not in xll:
            xll.append(x)
        if y not in yll:
            yll.append(y)
        if size not in sizes:
            sizes.append(size)
        if nodata not in nodatas:
            nodatas.append(nodata)
            
        counter+=1

In [25]:
print(cols)
print(rows)
print(xll)
print(yll)
print(sizes)
print(nodatas)

['720']
['360']
['-180']
['-90']
['0.5']
['-9999']


## Membersihkan file dari metadata

In [17]:
folders = ['image', 'aim', 'message', 'minicam']
for folder in folders:
    for file in os.listdir(f'./data/2005-2100/{folder}/updated_states'):
        with open(f"./data/2005-2100/{folder}/updated_states/{file}", 'r') as readfile:
            text = readfile.read()
            new_text = re.sub("ncols\s+(.+?)\s+nrows\s+(.+?)\s+xllcorner\s+(.+?)\s+yllcorner\s+(.+?)\s+cellsize\s+(.+?)\s+NODATA_value\s+(.+?)\s+", "", text)
        with open(f"./data/2005-2100/{folder}/updated_states/{file}", 'w') as writefile:
            writefile.write(new_text)

In [8]:
lat83lon_39 = pd.read_csv('./data/1500-2004/lu/lat83.75lon-39.75.lu', sep=' ')
lat83lon_39

year   cp   pc   pv   vp   vc   cv   sc   cs   sp   ps   vs  sbh  f_sbh  \
0    1500  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
1    1501  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
2    1502  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
3    1503  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
4    1504  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
..    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...   
500  2000  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
501  2001  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
502  2002  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
503  2003  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   
504  2004  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0    0.0   

     vbh  f_vbh  sbh2  f_sbh2  vbh2  f_vbh2  sbh3  f_sbh3  
0    0.0    0.0   0.0     0.0   0.0     0.0   0.0     0.0  
1    0.0    0.0   0.0     0.0   0.0     0.0   0.0     0.0  
2    0.0    0.0   0.0     0.0   0.0     0.0   0.0     0.0  
3    0.0    0.0   0.0     0.0   0.0     0.0   0.0     0.0  
4    0.0    0.0   0.0     0.0   0.0     0.0   0.0     0.0  
..   ...    ...   ...     ...   ...     ...   ...     ...  
500  0.0    0.0   0.0     0.0   0.0     0.0   0.0     0.0  
501  0.0    0.0   0.0     0.0   0.0     0.0   0.0     0.0  
502  0.0    0.0   0.0     0.0   0.0     0.0   0.0     0.0  
503  0.0    0.0   0.0     0.0   0.0     0.0   0.0     0.0  
504  0.0    0.0   0.0     0.0   0.0     0.0   0.0     0.0  

[505 rows x 22 columns]

## Menyamakan format nama data PFT

In [12]:
path_data = './data/PFT/1700-dst'
new_num = np.arange(1700, 1993)
count = 0
for file in os.listdir(path_data):
    # print(f"{path_data}/LAND_COV_scen_{new_num[count]}.nc")
    os.rename(f"{path_data}/{file}", f"{path_data}/LAND_COV_scen_{new_num[count]}.nc")
    count+=1

## Konstanta

In [2]:
EquCarbon = np.array([
    #PFT 1     2     3     4     5     6  7  8   9  10  11
    [  200,  160,  160,  135,   90,   90,27,27,  7, 18,  3], # Primary   - Veg
    [  150,  120,  120,  100,   68,   68,27,27,  7, 18,  0], # Secondary - Veg
    [   18,   18,    7,    7,    7,    7,18, 7,  7, 18,  7], # Pasture   - Veg
    [    5,    5,    5,    5,    5,    5, 5, 5,  3,  5,  1], # Crop      - Veg
    [  117,  117,  134,  134,  206,  206,69,69,189, 42,204], # Primary   - Soil
    [   88,   88,  120,  120,  185,  185,69,69,189, 42,204], # Secondary - Soil
    [87.75,87.75,100.5,100.5,154.5,154.5,69,69,189, 42,204], # Pasture   - Soil
    [   58,   58,   67,   67,  103,  103,34,34, 94, 21,101]  # Crop      - Soil
])

In [3]:
Harvest = np.array([
   #PFT 1    2    3    4    5    6    7    8    9   10   11
    [ 0.9, 0.9, 0.4, 0.4, 0.4, 0.4,   1,   1,   1,   1,   1], # Fraction of roundwood assigned to decay pools after harvest, 1yr
    [0.04,0.04,0.24,0.24,0.24,0.24,   0,   0,   0,   0,   0], # Fraction of roundwoodassigned to decay pools after harvest, 10yr
    [0.06,0.06,0.36,0.36,0.36,0.36,   0,   0,   0,   0,   0], # Fraction of roundwood assigned to decay pools after harvest, 100yr
    [0.79,0.86,0.81,0.78,0.87,0.87,0.86,0.78,0.78,0.86,0.87], # Fraction of vegetation carbon transferred dead to soil at clearing for primary forest
    [0.71,0.81,0.75,0.70,0.82,0.82,0.81,0.70,0.70,0.81,0.82], # Fraction of vegetation carbon transferred dead to soil at clearing for secondary forest
    [  76,  76,  67,  67, 175, 175,  45,  35,  95,  27, 173], # Minimum soil C following harvest
    [   5,   5,  10,  10,  15,  15,   5,  10,  10,   5,  15] # Time of soil carbon to reach minimum (as found following harvest)
])

In [6]:
Clearing = np.array([
   #PFT 1    2    3    4    5    6   7   8   9  10  11
    [ 0.4, 0.4, 0.4, 0.4, 0.4, 0.4,0.4,0.4,0.5,0.5,0.4], # Fraction of vegetation carbon assigned to decay pools after clearing, 1yr
    [0.27,0.27, 0.2, 0.2, 0.2, 0.2,0.1,0.1,  0,  0,0.1], # Fraction of vegetation carbon assigned to decay pools after clearing, 10yr
    [   0,   0,0.07,0.07,0.07,0.07,  0,  0,  0,  0,  0], # Fraction of vegetation carbon assigned to decay pools after clearing, 100yr
    [0.33,0.33,0.33,0.33,0.33,0.33,0.5,0.5,0.5,0.5,0.5], # Fraction of vegetation carbon transferred dead to soil at clearing (1-SUM(product pools))
    [  70,  70,  80,  80, 160, 160, 41, 41,113, 25,121], # Soil carbon after initial, rapid loss after clearing
    [   3,   3,  15,  15,  50,  50,  3, 15, 15,  3, 15], # Time of rapid soil carbon loss
    [  15,  15,  30,  30,  50,  50, 15, 30, 30, 15, 30] # Time of soil carbon to reach minimum (as found under cultivation)
])

In [7]:
RecoveryConstants = np.array([
 #PFT 1  2  3  4  5  6  7  8  9 10 11
    [50,50,50,50,50,50,25,50,10, 5,50], # Time required for biomass carbon to recover (to secondary land) after abandoned
    [15,15,40,40,35,35,15,45,45,15,45] # Time required for soil carbon to recover (to secondary land) after abandoned
])

## Percobaan

In [6]:
lon_coordinates = np.linspace(-179.75, 179.75, 720)

In [7]:
lat_coordinates = np.linspace(89.75, -89.75, 360)

In [61]:
gflvp = pd.read_csv('./data/1500-2004/updated_states/gflvp.1500.txt', sep=' ', names = lon_coordinates, header=None, index_col=False)

In [ ]:
gflvp.set_index(lat_coordinates, inplace=True)

In [44]:
gflvp.loc[-0.25, 109.25]

4e-06

In [45]:
coor1 = pd.read_csv('./data/1500-2004/lu/lat-0.25lon109.25.lu', sep=' ')
coor1

year   cp   pc   pv        vp        vc   cv        sc   cs        sp  \
0    1500  0.0  0.0  0.0  0.000004  0.000004  0.0  0.000000  0.0  0.000000   
1    1501  0.0  0.0  0.0  0.000000  0.000000  0.0  0.000004  0.0  0.000003   
2    1502  0.0  0.0  0.0  0.000000  0.000000  0.0  0.000004  0.0  0.000004   
3    1503  0.0  0.0  0.0  0.000000  0.000000  0.0  0.000004  0.0  0.000004   
4    1504  0.0  0.0  0.0  0.000000  0.000000  0.0  0.000004  0.0  0.000004   
..    ...  ...  ...  ...       ...       ...  ...       ...  ...       ...   
500  2000  0.0  0.0  0.0  0.000000  0.000000  0.0  0.003567  0.0  0.000027   
501  2001  0.0  0.0  0.0  0.000000  0.000000  0.0  0.003567  0.0  0.000027   
502  2002  0.0  0.0  0.0  0.000000  0.000000  0.0  0.003567  0.0  0.000027   
503  2003  0.0  0.0  0.0  0.000000  0.000000  0.0  0.003567  0.0  0.000027   
504  2004  0.0  0.0  0.0  0.000000  0.000000  0.0  0.003567  0.0  0.000027   

      ps        vs          sbh     f_sbh           vbh     f_vbh  sbh2  \
0    0.0  0.000011     0.000000  0.000000    550.027251  0.000011   0.0   
1    0.0  0.000011     0.000000  0.000000    550.579441  0.000011   0.0   
2    0.0  0.000011     0.001545  0.000000    550.653960  0.000011   0.0   
3    0.0  0.000011     0.002364  0.000000    551.203053  0.000011   0.0   
4    0.0  0.000011     0.004868  0.000000    551.751528  0.000011   0.0   
..   ...       ...          ...       ...           ...       ...   ...   
500  0.0  0.001222  2515.509313  0.000139  60179.590892  0.001222   0.0   
501  0.0  0.001117  2505.843729  0.000136  54988.624065  0.001117   0.0   
502  0.0  0.001150  3005.121484  0.000159  56628.777960  0.001150   0.0   
503  0.0  0.001113  3025.834893  0.000155  54808.908559  0.001113   0.0   
504  0.0  0.001082  3038.193309  0.000152  53277.215818  0.001082   0.0   

     f_sbh2  vbh2  f_vbh2  sbh3  f_sbh3  
0       0.0   0.0     0.0   0.0     0.0  
1       0.0   0.0     0.0   0.0     0.0  
2       0.0   0.0     0.0   0.0     0.0  
3       0.0   0.0     0.0   0.0     0.0  
4       0.0   0.0     0.0   0.0     0.0  
..      ...   ...     ...   ...     ...  
500     0.0   0.0     0.0   0.0     0.0  
501     0.0   0.0     0.0   0.0     0.0  
502     0.0   0.0     0.0   0.0     0.0  
503     0.0   0.0     0.0   0.0     0.0  
504     0.0   0.0     0.0   0.0     0.0  

[505 rows x 22 columns]

In [43]:
gflvp.loc[0.25, 109.25]

0.000394

In [42]:
coor2 = pd.read_csv('./data/1500-2004/lu/lat0.25lon109.25.lu', sep=' ')
coor2

year   cp   pc   pv        vp        vc   cv        sc        cs  \
0    1500  0.0  0.0  0.0  0.000394  0.000167  0.0  0.000000  0.000164   
1    1501  0.0  0.0  0.0  0.000000  0.000000  0.0  0.000167  0.000164   
2    1502  0.0  0.0  0.0  0.000000  0.000000  0.0  0.000167  0.000164   
3    1503  0.0  0.0  0.0  0.000000  0.000000  0.0  0.000167  0.000164   
4    1504  0.0  0.0  0.0  0.000000  0.000000  0.0  0.000167  0.000164   
..    ...  ...  ...  ...       ...       ...  ...       ...       ...   
500  2000  0.0  0.0  0.0  0.000000  0.000000  0.0  0.024142  0.019027   
501  2001  0.0  0.0  0.0  0.000000  0.000000  0.0  0.024482  0.019368   
502  2002  0.0  0.0  0.0  0.000000  0.000000  0.0  0.024823  0.019709   
503  2003  0.0  0.0  0.0  0.000000  0.000000  0.0  0.025163  0.020049   
504  2004  0.0  0.0  0.0  0.000000  0.000000  0.0  0.025505  0.020390   

           sp        ps        vs        sbh     f_sbh           vbh  \
0    0.000000  0.000389  0.000012   0.000000  0.000000    585.758287   
1    0.000395  0.000389  0.000012   0.000000  0.000000    586.346349   
2    0.000395  0.000390  0.000012   0.056149  0.000000    586.425708   
3    0.000396  0.000390  0.000012   0.056793  0.000000    587.010471   
4    0.000395  0.000390  0.000012   0.057429  0.000000    587.594577   
..        ...       ...       ...        ...       ...           ...   
500  0.004146  0.004107  0.001274  19.093091  0.000008  62064.345929   
501  0.004148  0.004110  0.001164  18.673381  0.000008  56710.804037   
502  0.004151  0.004112  0.001198  17.674289  0.000007  58402.325651   
503  0.004153  0.004115  0.001160  15.941026  0.000007  56525.460050   
504  0.004156  0.004117  0.001128  13.799704  0.000006  54945.796468   

        f_vbh  sbh2  f_sbh2  vbh2  f_vbh2  sbh3  f_sbh3  
0    0.000012   0.0     0.0   0.0     0.0   0.0     0.0  
1    0.000012   0.0     0.0   0.0     0.0   0.0     0.0  
2    0.000012   0.0     0.0   0.0     0.0   0.0     0.0  
3    0.000012   0.0     0.0   0.0     0.0   0.0     0.0  
4    0.000012   0.0     0.0   0.0     0.0   0.0     0.0  
..        ...   ...     ...   ...     ...   ...     ...  
500  0.001274   0.0     0.0   0.0     0.0   0.0     0.0  
501  0.001164   0.0     0.0   0.0     0.0   0.0     0.0  
502  0.001198   0.0     0.0   0.0     0.0   0.0     0.0  
503  0.001160   0.0     0.0   0.0     0.0   0.0     0.0  
504  0.001128   0.0     0.0   0.0     0.0   0.0     0.0  

[505 rows x 22 columns]

In [19]:
image = pd.read_csv('./data/2005-2100/image/updated_states/gflvp.2005.txt', sep=' ', names = lon_coordinates, header=None, index_col=False)
image

-179.75  -179.25  -178.75  -178.25  -177.75  -177.25  -176.75  -176.25  \
0        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
3        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4        0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
..       ...      ...      ...      ...      ...      ...      ...      ...   
355      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
356      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
357      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
358      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
359      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

     -175.75  -175.25  ...   175.25   175.75   176.25   176.75   177.25  \
0        0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
1        0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
2        0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
3        0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
4        0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
..       ...      ...  ...      ...      ...      ...      ...      ...   
355      0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
356      0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
357      0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
358      0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   
359      0.0      0.0  ...      0.0      0.0      0.0      0.0      0.0   

      177.75   178.25   178.75   179.25   179.75  
0        0.0      0.0      0.0      0.0      0.0  
1        0.0      0.0      0.0      0.0      0.0  
2        0.0      0.0      0.0      0.0      0.0  
3        0.0      0.0      0.0      0.0      0.0  
4        0.0      0.0      0.0      0.0      0.0  
..       ...      ...      ...      ...      ...  
355      0.0      0.0      0.0      0.0      0.0  
356      0.0      0.0      0.0      0.0      0.0  
357      0.0      0.0      0.0      0.0      0.0  
358      0.0      0.0      0.0      0.0      0.0  
359      0.0      0.0      0.0      0.0      0.0  

[360 rows x 720 columns]

In [26]:
aim = pd.read_csv('./data/2005-2100/aim/updated_states/gflvp.2005.txt', sep=' ', names = lon_coordinates, header=None, index_col=False)

In [21]:
message = pd.read_csv('./data/2005-2100/message/updated_states/gflvp.2005.txt', sep=' ', names = lon_coordinates, header=None, index_col=False)

In [22]:
minicam = pd.read_csv('./data/2005-2100/minicam/updated_states/gflvp.2005.txt', sep=' ', names = lon_coordinates, header=None, index_col=False)

In [59]:
class CarbonPool:
    delta = []
    equilibrium = []

In [60]:
Biomass = CarbonPool()

In [34]:
(aim != message).sum().sum()

12839

In [33]:
(aim != minicam).sum().sum()

7753

In [35]:
(aim != image).sum().sum()

5917

In [36]:
(message != minicam).sum().sum()

12404

In [37]:
(message != image).sum().sum()

10410

In [38]:
(image != minicam).sum().sum()

5909

## PFT netcdf

In [3]:
ds = nc.Dataset('../data/1500-2004/PFT/LAND_COV_scen_1992.nc')

In [4]:
ds

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    title: Historic land cover reconstruction
    institution: Max Planck Institute for Meteorology 
    authors: J. Pongratz, C. Reick, T. Raddatz, M. Claussen
    dimensions(sizes): longitude(720), latitude(360), vegtype(14), time(1)
    variables(dimensions): float32 longitude(longitude), float32 latitude(latitude), int32 vegtype(vegtype), int32 time(time), float32 vegfract(time, vegtype, latitude, longitude)
    groups: 

In [5]:
ds['vegtype'][:]

masked_array(data=[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
             mask=False,
       fill_value=999999)

In [31]:
pft1 = ds['vegfract'][:,0,:,:].data

In [32]:
[lat101] = ds['vegfract'][:,0,100,:].data
#lat101

In [33]:
[lat360] = ds['vegfract'][:,0,359,:].data
#lat360

In [13]:
lat10.shape

(720,)

In [5]:
ds['vegfract']

<class 'netCDF4._netCDF4.Variable'>
float32 vegfract(time, vegtype, latitude, longitude)
    long_name: Fraction of grid cell covered by vegtype
    missing_value: -9e+20
    units: fraction
unlimited dimensions: time
current shape = (1, 14, 360, 720)
filling on, default _FillValue of 9.969209968386869e+36 used

In [14]:
def sum_coor_pfts(lat, lon):
    area_counter = 0
    veg_counter = 0
    for time in ds['vegfract'][:,:,:,:].data:
        for veg in time:
            veg_counter+=1
            print(f"veg type {veg_counter}: {veg[100, 215]}")
            area_counter += veg[100, 215]
    return(area_counter)

In [15]:
sum_coor_pfts(100,215)

veg type 1: 0.026399483904242516
veg type 2: 0.0
veg type 3: 0.13704395294189453
veg type 4: 0.16385698318481445
veg type 5: 0.16385698318481445
veg type 6: 0.0
veg type 7: 0.0
veg type 8: 0.0
veg type 9: 0.43851059675216675
veg type 10: 0.0
veg type 11: 0.0
veg type 12: 0.03768610209226608
veg type 13: 0.02410000003874302
veg type 14: 0.0


0.9914541020989418

In [8]:
sum_coor_pfts(96,213)

0.9914541020989418

In [9]:
sum_coor_pfts(0,0)

0.9914541020989418

In [18]:
veg_counter = 0
for time in ds['vegfract'][:,:,:,:].data:
    for veg in time:
        veg_counter +=1
        print(f'VEG TYPE {veg_counter}')
        lat_counter = 0
        for lat in veg:
            lat_counter+=1
            missing = 0
            filled = 0
            zero = 0
            for lon in lat:
                if (lon >= -1) & (lon <= 1) & (lon != 0):
                    filled +=1
                    # print(lon)
                    # counter+=1
                elif (lon == 0):
                    zero+=1
                else:
                    #print(lon)
                    missing+=1
            #print(f"total: {missing+filled+zero}")
            print(f"P{lat_counter}: \t{filled} \t{missing} \t{zero}")
            #print(f"lat {lat_counter}: \tmissing:{missing}\tfilled:{filled}\tzero:{zero}")
        print()
        print()
        print()
        break

VEG TYPE 1
P1: 	0 	0 	720
P2: 	0 	0 	720
P3: 	0 	0 	720
P4: 	0 	0 	720
P5: 	0 	0 	720
P6: 	0 	0 	720
P7: 	0 	0 	720
P8: 	0 	0 	720
P9: 	0 	0 	720
P10: 	0 	27 	693
P11: 	0 	47 	673
P12: 	0 	57 	663
P13: 	0 	69 	651
P14: 	0 	77 	643
P15: 	0 	87 	633
P16: 	0 	100 	620
P17: 	0 	131 	589
P18: 	0 	145 	575
P19: 	0 	171 	549
P20: 	0 	180 	540
P21: 	0 	173 	547
P22: 	0 	167 	553
P23: 	0 	153 	567
P24: 	0 	154 	566
P25: 	0 	157 	563
P26: 	0 	178 	542
P27: 	0 	197 	523
P28: 	0 	188 	532
P29: 	0 	200 	520
P30: 	0 	217 	503
P31: 	0 	241 	479
P32: 	0 	272 	448
P33: 	0 	268 	452
P34: 	0 	296 	424
P35: 	0 	330 	390
P36: 	0 	333 	387
P37: 	0 	336 	384
P38: 	0 	360 	360
P39: 	0 	378 	342
P40: 	0 	429 	291
P41: 	0 	457 	263
P42: 	0 	479 	241
P43: 	0 	505 	215
P44: 	0 	522 	198
P45: 	0 	542 	178
P46: 	0 	566 	154
P47: 	0 	607 	113
P48: 	0 	672 	48
P49: 	0 	713 	7
P50: 	0 	714 	6
P51: 	0 	716 	4
P52: 	0 	712 	8
P53: 	0 	716 	4
P54: 	0 	715 	5
P55: 	0 	718 	2
P56: 	0 	720 	0
P57: 	0 	720 	0
P58: 	0 	719 	1

## Menggabungkan seluruh data PFT

In [37]:
ds_combine = xarray.open_mfdataset('../latihan/PFT/LAND_COV_scen_*.nc',combine = 'nested', concat_dim="time")

In [38]:
ds_combine

<xarray.Dataset>
Dimensions:    (longitude: 720, latitude: 360, vegtype: 14, time: 100)
Coordinates:
  * longitude  (longitude) float32 -179.8 -179.2 -178.8 ... 178.8 179.2 179.8
  * latitude   (latitude) float32 -89.75 -89.25 -88.75 ... 88.75 89.25 89.75
  * vegtype    (vegtype) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  * time       (time) int32 1500 1501 1502 1503 1504 ... 1596 1597 1598 1599
Data variables:
    vegfract   (time, vegtype, latitude, longitude) float32 dask.array<chunksize=(1, 14, 360, 720), meta=np.ndarray>
Attributes:
    title:        Historic land cover reconstruction
    institution:  Max Planck Institute for Meteorology 
    authors:      J. Pongratz, C. Reick, T. Raddatz, M. Claussen

In [39]:
ds_combine['vegfract']

<xarray.DataArray 'vegfract' (time: 100, vegtype: 14, latitude: 360,
                              longitude: 720)>
dask.array<concatenate, shape=(100, 14, 360, 720), dtype=float32, chunksize=(1, 14, 360, 720), chunktype=numpy.ndarray>
Coordinates:
  * longitude  (longitude) float32 -179.8 -179.2 -178.8 ... 178.8 179.2 179.8
  * latitude   (latitude) float32 -89.75 -89.25 -88.75 ... 88.75 89.25 89.75
  * vegtype    (vegtype) int32 1 2 3 4 5 6 7 8 9 10 11 12 13 14
  * time       (time) int32 1500 1501 1502 1503 1504 ... 1596 1597 1598 1599
Attributes:
    long_name:  Fraction of grid cell covered by vegtype
    units:      fraction

In [21]:
latihan = nc.Dataset('../latihan/LAND_COV_scen_1700_1992_001.nc')

In [27]:
latihan

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    title: Historic land cover reconstruction
    institution: Max Planck Institute for Meteorology 
    authors: J. Pongratz, C. Reick, T. Raddatz, M. Claussen
    dimensions(sizes): longitude(720), latitude(360), vegtype(14), time(1)
    variables(dimensions): float32 longitude(longitude), float32 latitude(latitude), int32 vegtype(vegtype), int32 time(time), float32 vegfract(time, vegtype, latitude, longitude)
    groups: 

In [55]:
latihan

## PFT Mask

In [23]:
ds1 = nc.Dataset('./data/PFT/1500-1699/LAND_COV_scen_800_1699_0701.nc')
ds2 = nc.Dataset('./data/PFT/1700-dst/LAND_COV_scen_1700_1992_001.nc')
ds3 = nc.Dataset('./data/PFT/1700-dst/LAND_COV_scen_1700_1992_293.nc')

In [31]:
(ds3['vegfract'][:,0,:,:].mask == ds2['vegfract'][:,0,:,:].mask).sum()

259200

In [38]:
arr1 = np.zeros((2,2,4))
arr2 = np.zeros((2,2,4))

In [39]:
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [41]:
np.append(arr1, arr2, axis=0)

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [42]:
carbon_excess = np.zeros((1,7,4,4,11))

In [44]:
carbon_excess.shape

(1, 7, 4, 4, 11)

In [45]:
temp = np.zeros((1,7,4,4,11))

In [46]:
carbon_excess = np.append(carbon_excess, temp, axis=0)

In [52]:
temp = carbon_excess[-1, :,:,:,:]
temp.shape

(7, 4, 4, 11)

In [54]:
temp[np.newaxis, :].shape

(1, 7, 4, 4, 11)

In [ ]:
carbon_excess[-1, :,:,:,:]

In [56]:
a = np.array([1])

In [57]:
a = np.append(a, np.array([2]))

In [58]:
a

array([1, 2])

In [59]:
a[-1]

2

In [60]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6],
              [7,8]])

In [63]:
np.append(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
np.append(a,b, axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [3]:
A = np.array([[2,2],[3,3]])
B = np.array([[2,3],[2,3]])
A**B

array([[ 4,  8],
       [ 9, 27]])

In [4]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [10]:
num1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
num2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
num3 = np.array([[21,22,23],[24,25,26],[27,28,29]])

In [11]:
num1.shape

(3, 3)

In [18]:
nums = np.array([num1, num2, num3])

In [19]:
nums.shape

(3, 3, 3)

In [16]:
a = np.array([num[2,2] for num in nums])

In [17]:
a.shape

(3,)

In [40]:
b = np.array([[[1]],[[2]],[[3]]])
b/b.sum()

array([[[0.16666667]],

       [[0.33333333]],

       [[0.5       ]]])

In [21]:
b.shape

(3, 1, 1)

In [22]:
b_new = np.squeeze(b)
b_new.shape

(3,)

In [ ]:
for filename in os.listdir("../../latihan")
lat = re.search('lat(.+?)lon', filename).group(1)
lon = re.search('lon(.+?)\.lu', filename).group(1)