In [1]:
import pandas as pd
import os
import re
import numpy as np
import netCDF4 as nc
import xarray
pd.options.display.max_columns = 22

In [6]:
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
data_path = "../latihan"
filename = "lat-0.25lon-77.75.lu"
column_list = np.append(np.arange(1,12), np.array([13,15,17,19,21]))
transitions = np.loadtxt(f"{data_path}/lu/{filename}", skiprows=1, usecols=column_list)
transitions.shape

(505, 16)

In [5]:
coor = pd.read_csv('./data/1500-2004/lu/lat-0.25lon-77.75.lu', sep=' ')
# coor.drop(['year','sbh','vbh','sbh2','vbh2','sbh3'], axis=1, inplace=True)
# coor.drop(['cp', 'pc', 'pv', 'vp', 'vc','cv','sc','cs','sp','ps','sbh','vbh','sbh2','vbh2','sbh3'], axis=1, inplace=True)
coor

year   cp   pc   pv        vp   vc   cv        sc        cs        sp  \
0    1500  0.0  0.0  0.0  0.000063  0.0  0.0  0.000000  0.000000  0.000000   
1    1501  0.0  0.0  0.0  0.000067  0.0  0.0  0.000000  0.000000  0.000000   
2    1502  0.0  0.0  0.0  0.000071  0.0  0.0  0.000000  0.000000  0.000000   
3    1503  0.0  0.0  0.0  0.000076  0.0  0.0  0.000000  0.000000  0.000000   
4    1504  0.0  0.0  0.0  0.000079  0.0  0.0  0.000000  0.000000  0.000000   
..    ...  ...  ...  ...       ...  ...  ...       ...       ...       ...   
500  2000  0.0  0.0  0.0  0.000000  0.0  0.0  0.006432  0.009210  0.017713   
501  2001  0.0  0.0  0.0  0.000000  0.0  0.0  0.006247  0.009025  0.017646   
502  2002  0.0  0.0  0.0  0.000000  0.0  0.0  0.006062  0.008839  0.017578   
503  2003  0.0  0.0  0.0  0.000000  0.0  0.0  0.005877  0.008655  0.017511   
504  2004  0.0  0.0  0.0  0.000000  0.0  0.0  0.005691  0.008469  0.017443   

           ps        vs            sbh     f_sbh          vbh     f_vbh  sbh2  \
0    0.000000  0.000000       0.000000  0.000000     0.000000  0.000000   0.0   
1    0.000004  0.000094       0.000000  0.000000  4129.091591  0.000094   0.0   
2    0.000008  0.000094       0.007079  0.000000  4136.057691  0.000094   0.0   
3    0.000013  0.000094       0.014473  0.000000  4142.892461  0.000094   0.0   
4    0.000017  0.000094       0.032882  0.000000  4148.492157  0.000094   0.0   
..        ...       ...            ...       ...          ...       ...   ...   
500  0.018725  0.000000       0.000000  0.000000     0.000000  0.000000   0.0   
501  0.018658  0.000000   41517.632709  0.001321     0.000000  0.000000   0.0   
502  0.018590  0.000000  128093.011687  0.004137     0.000000  0.000000   0.0   
503  0.018523  0.000000  148441.323604  0.004870     0.000000  0.000000   0.0   
504  0.018455  0.000000  146658.100667  0.004899     0.000000  0.000000   0.0   

     f_sbh2  vbh2  f_vbh2  sbh3  f_sbh3  
0       0.0   0.0     0.0   0.0     0.0  
1       0.0   0.0     0.0   0.0     0.0  
2       0.0   0.0     0.0   0.0     0.0  
3       0.0   0.0     0.0   0.0     0.0  
4       0.0   0.0     0.0   0.0     0.0  
..      ...   ...     ...   ...     ...  
500     0.0   0.0     0.0   0.0     0.0  
501     0.0   0.0     0.0   0.0     0.0  
502     0.0   0.0     0.0   0.0     0.0  
503     0.0   0.0     0.0   0.0     0.0  
504     0.0   0.0     0.0   0.0     0.0  

[505 rows x 22 columns]

In [19]:
coor.sum()[1:]

vs        0.004132
f_sbh     0.059584
f_vbh     0.004132
f_sbh2    0.000000
f_vbh2    0.000000
f_sbh3    0.000000
dtype: float64

In [17]:
coor1 = pd.read_csv('./data/1500-2004/lu/lat-0.25lon109.25.lu', sep=' ')
coor1.drop(['cp', 'pc', 'pv', 'vp', 'vc','cv','sc','cs','sp','ps','sbh','vbh','sbh2','vbh2','sbh3'], axis=1, inplace=True)
coor1

year        vs     f_sbh     f_vbh  f_sbh2  f_vbh2  f_sbh3
0    1500  0.000011  0.000000  0.000011     0.0     0.0     0.0
1    1501  0.000011  0.000000  0.000011     0.0     0.0     0.0
2    1502  0.000011  0.000000  0.000011     0.0     0.0     0.0
3    1503  0.000011  0.000000  0.000011     0.0     0.0     0.0
4    1504  0.000011  0.000000  0.000011     0.0     0.0     0.0
..    ...       ...       ...       ...     ...     ...     ...
500  2000  0.001222  0.000139  0.001222     0.0     0.0     0.0
501  2001  0.001117  0.000136  0.001117     0.0     0.0     0.0
502  2002  0.001150  0.000159  0.001150     0.0     0.0     0.0
503  2003  0.001113  0.000155  0.001113     0.0     0.0     0.0
504  2004  0.001082  0.000152  0.001082     0.0     0.0     0.0

[505 rows x 7 columns]

In [18]:
coor1.sum()[1:]

vs        0.126292
f_sbh     0.002633
f_vbh     0.126292
f_sbh2    0.000000
f_vbh2    0.000000
f_sbh3    0.000000
dtype: float64

In [22]:
a = np.zeros((2,2,6))
a

array([[[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]])

In [9]:
a = np.array([[1,2,3],
              [4,5,6]])
a / np.tile(a.sum(axis=1)[:, np.newaxis], (1,3))

array([[0.16666667, 0.33333333, 0.5       ],
       [0.26666667, 0.33333333, 0.4       ]])

In [11]:
a = np.array([0,1,2,3,4,5,6,7,8,9,10])
a[:6].shape

(6,)

In [12]:
a[6:-1]

array([6, 7, 8, 9])

In [15]:
b = np.array([0.1,0.2,0.3,0.4])
np.tile(b[:,np.newaxis,np.newaxis],(1,4,11))[:,0,:]

array([[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1],
       [0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2],
       [0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3],
       [0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4]])

In [3]:
11//2

5