In [2]:
import numpy as np
import pandas as pd
import os
import netCDF4 as nc
from pyproj import Proj
from shapely.geometry import shape
import re

In [21]:
from lib.Coordinate import Coordinate
#from lib import Constants as c

In [20]:
tuple(np.arange(1,22))

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21)

In [4]:
col_list = tuple(np.linspace(1,21,21, dtype=int))
col_list

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21)

In [6]:
transitions = np.loadtxt('./data/1500-2004/lu/lat-0.25lon109.25.lu', skiprows=1, usecols=col_list)
transitions[0]

array([0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.00000000e-06,
       4.00000000e-06, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 1.10000000e-05, 0.00000000e+00,
       0.00000000e+00, 5.50027251e+02, 1.10000000e-05, 0.00000000e+00,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])

In [39]:
transitions.shape

(505, 21)

In [6]:
initial_crop = np.loadtxt('./data/1500-2004/updated_states/gcrop.1500.txt')
initial_crop

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [7]:
initial_virgin = np.loadtxt('./data/1500-2004/updated_states/gothr.1500.txt')
initial_virgin

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [8]:
initial_pasture = np.loadtxt('./data/1500-2004/updated_states/gpast.1500.txt')
initial_pasture

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
initial_sec = np.loadtxt('./data/1500-2004/updated_states/gsecd.1500.txt')
initial_sec

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [14]:
initial_states = np.array([initial_virgin[180,578], initial_sec[180,578], initial_crop[180,578], initial_pasture[180,578]])

In [8]:
ds = nc.Dataset('./data/1500-2004/PFT/LAND_COV_scen_1500.nc')
#ds['vegfract'][:,0,:,:]
ds['vegfract'][0,:11,180,578].data
# [pft] = 
# pft

array([0.91518563, 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        ], dtype=float32)

In [23]:
ds1 = nc.Dataset('./data/PFT/1700-dst/LAND_COV_scen_1700_1992_001.nc')
ds1['vegfract'][:,:,:,:].data.shape

(1, 14, 360, 720)

In [18]:
ds['vegfract'][:,:,:,:].data

array([[[[ 0.e+00,  0.e+00,  0.e+00, ...,  0.e+00,  0.e+00,  0.e+00],
         [ 0.e+00,  0.e+00,  0.e+00, ...,  0.e+00,  0.e+00,  0.e+00],
         [ 0.e+00,  0.e+00,  0.e+00, ...,  0.e+00,  0.e+00,  0.e+00],
         ...,
         [-9.e+20, -9.e+20, -9.e+20, ..., -9.e+20, -9.e+20, -9.e+20],
         [-9.e+20, -9.e+20, -9.e+20, ..., -9.e+20, -9.e+20, -9.e+20],
         [-9.e+20, -9.e+20, -9.e+20, ..., -9.e+20, -9.e+20, -9.e+20]],

        [[ 0.e+00,  0.e+00,  0.e+00, ...,  0.e+00,  0.e+00,  0.e+00],
         [ 0.e+00,  0.e+00,  0.e+00, ...,  0.e+00,  0.e+00,  0.e+00],
         [ 0.e+00,  0.e+00,  0.e+00, ...,  0.e+00,  0.e+00,  0.e+00],
         ...,
         [-9.e+20, -9.e+20, -9.e+20, ..., -9.e+20, -9.e+20, -9.e+20],
         [-9.e+20, -9.e+20, -9.e+20, ..., -9.e+20, -9.e+20, -9.e+20],
         [-9.e+20, -9.e+20, -9.e+20, ..., -9.e+20, -9.e+20, -9.e+20]],

        [[ 0.e+00,  0.e+00,  0.e+00, ...,  0.e+00,  0.e+00,  0.e+00],
         [ 0.e+00,  0.e+00,  0.e+00, ...,  0.e+00,  0.e+00

In [24]:
lat_025lon10925 = Coordinate(transitions, initial_states, pft)
print(lat_025lon10925.transitions)
print()
print(lat_025lon10925.states)
print()
print(lat_025lon10925.pft)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]

[0.772427 0.       0.003273 0.004111]

[0.91518563 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.02934653
 0.00208263 0.00861766]


array([[200.  , 160.  , 160.  , 135.  ,  90.  ,  90.  ,  27.  ,  27.  ,
          7.  ,  18.  ,   3.  ],
       [150.  , 120.  , 120.  , 100.  ,  68.  ,  68.  ,  27.  ,  27.  ,
          7.  ,  18.  ,   0.  ],
       [ 18.  ,  18.  ,   7.  ,   7.  ,   7.  ,   7.  ,  18.  ,   7.  ,
          7.  ,  18.  ,   7.  ],
       [  5.  ,   5.  ,   5.  ,   5.  ,   5.  ,   5.  ,   5.  ,   5.  ,
          3.  ,   5.  ,   1.  ],
       [117.  , 117.  , 134.  , 134.  , 206.  , 206.  ,  69.  ,  69.  ,
        189.  ,  42.  , 204.  ],
       [ 88.  ,  88.  , 120.  , 120.  , 185.  , 185.  ,  69.  ,  69.  ,
        189.  ,  42.  , 204.  ],
       [ 87.75,  87.75, 100.5 , 100.5 , 154.5 , 154.5 ,  69.  ,  69.  ,
        189.  ,  42.  , 204.  ],
       [ 58.  ,  58.  ,  67.  ,  67.  , 103.  , 103.  ,  34.  ,  34.  ,
         94.  ,  21.  , 101.  ]])

In [3]:
time_biomass = np.array([ # virgin
     [# clearing
      [0,0,0,0,0,0,0,0,0,0,0],
      # harvest
      [0,0,0,0,0,0,0,0,0,0,0],
      # abandonment
      [0,0,0,0,0,0,0,0,0,0,0],
      # others
      [0,0,0,0,0,0,0,0,0,0,0]],
     # secondary
     [# clearing
      [0,0,0,0,0,0,0,0,0,0,0],
      # harvest
      [26.7,26.7,26.7,26.7,26.7,26.7,13.35,26.7,5.34,2.67,26.7],
      # abandonment
      [26.7,26.7,26.7,26.7,26.7,26.7,13.35,26.7,5.34,2.67,26.7],
      # others
      [0,0,0,0,0,0,0,0,0,0,0]],
     # pasture
     [# clearing
      [0,0,0,0,0,0,0,0,0,0,0],
      # harvest
      [0,0,0,0,0,0,0,0,0,0,0],
      # abandonment
      [0,0,0,0,0,0,0,0,0,0,0],
      # others
      [0,0,0,0,0,0,0,0,0,0,0]],
     # crop
     [# clearing
      [0,0,0,0,0,0,0,0,0,0,0],
      # harvest
      [0,0,0,0,0,0,0,0,0,0,0],
      # abandonment
      [0,0,0,0,0,0,0,0,0,0,0],
      # others
      [0,0,0,0,0,0,0,0,0,0,0]]])

In [6]:
time_biomass.dtype

dtype('float64')

In [5]:
np.array([[1,2,3],[1]])

C:\Users\Khalid\AppData\Local\Temp\ipykernel_928\2397497397.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array([[1,2,3],[1]])


array([list([1, 2, 3]), list([1])], dtype=object)

In [4]:
{"type": "Polygon", 
 "coordinates": [[
   [-102.05, 41.0], 
   [-102.05, 37.0], 
   [-109.05, 37.0], 
   [-109.05, 41.0]
 ]]}

{'type': 'Polygon',
 'coordinates': [[[-102.05, 41.0],
   [-102.05, 37.0],
   [-109.05, 37.0],
   [-109.05, 41.0]]]}

In [5]:
co = {"type": "Polygon", "coordinates": [
    [(-102.05, 41.0),
     (-102.05, 37.0),
     (-109.05, 37.0),
     (-109.05, 41.0)]]}
lon, lat = zip(*co['coordinates'][0])

In [7]:
lat

(41.0, 37.0, 37.0, 41.0)

In [8]:
zip(*co['coordinates'][0])

In [9]:
co['coordinates'][0]

[(-102.05, 41.0), (-102.05, 37.0), (-109.05, 37.0), (-109.05, 41.0)]

In [10]:
co['coordinates']

[[(-102.05, 41.0), (-102.05, 37.0), (-109.05, 37.0), (-109.05, 41.0)]]

In [16]:
coordinates = dict()
for filename in os.listdir('../latihan/lu'):
    # print(f"lat{re.search('lat(.+?)lon', filename).group(1)}")
    string = re.sub("(\.|lu)", "",filename)
    coordinates[f"{re.sub('-', '_', string)}"] = "hehe"

In [13]:
string = "lat-0.25lon6.25.lu"
string = re.sub("(\.|lu)", "", string)
string = re.sub("-", "_", string)

In [21]:
os.getcwd()

'C:\\Users\\Khalid\\Desktop\\Riset data\\LUHa\\LULCC'

In [31]:
base = "../latihan/pft"
reader(base)

['LAND_COV_scen_1500.nc', 'LAND_COV_scen_1501.nc', 'LAND_COV_scen_1502.nc']

In [30]:
def reader(path):
    filenames = []
    for file in os.listdir(path):
        filenames.append(file)
    return filenames

In [33]:
class halo:
    string = "hello"

In [34]:
coordinates = dict()
coordinates['string1'] = halo()

In [37]:
coordinates['string1'].string

'hello'